// TODO: Get actions from their api:
// https://trello.com/c/UR753bCs/67-api-endpoint-for-litcoin-values

export const LITCOIN_TYPES = {
  COMPLETE_SIGNUP_MODAL: 'COMPLETE_SIGNUP_MODAL',
  ENTERS_USERNAME: 'ENTERS_USERNAME',
  ENTERS_PASSWORD: 'ENTERS_PASSWORD',
  CREATED_ACCOUNT: 'CREATED_ACCOUNT',
  CHOSE_GENRE: 'CHOSE_GENRE',
  CHOSE_READER: 'CHOSE_READER',
  CHOSE_AUTHOR: 'CHOSE_AUTHOR',
}

export const ONBOARDING = {
  'COMPLETE_SIGNUP_MODAL': 10000,
  'ENTERS_USERNAME': 1000,
  'ENTERS_PASSWORD': 1000,
  'CREATED_ACCOUNT': 1000,
  'CHOSE_GENRE': 2000,
  'CHOSE_READER': 700,
  'CHOSE_AUTHOR': 700,
}

export default {
  LITCOIN_TYPES,
  ONBOARDING,
}
