stages:
- test
- deploy
      
.run_tests:
  stage: test
  script: run_tests.sh
  only:
  - master
  - staging
  - staging2

deploy_staging:
  only:
  - staging
  - staging2
  stage: deploy
  script: ./deploy.sh $CI_COMMIT_REF_NAME
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://$CI_COMMIT_REF_NAME.goread.com

deploy_apps:
  only:
  - master
  stage: deploy
  when: manual
  script: ./deploy.sh master
  environment:
    name: production
    url: https://www.goread.com
