version: '3.1'

services:
  goread-frontend:
    image: goread-frontend
    build: .
    environment:
      NODE_ENV: development
      SOCKET_URL: wss://localhost/ws/userprofile?subscribe-users
      REDIRECT_BASE_URL: https://localhost
      API_URL: https://localhost
      SESSION_COOKIE_DOMAIN: '.localhost'
      PORT: 3001
    ports:
      - 3001:3001